#!/bin/zsh


server="$1"
if [ $server = "" ]; then
  exit 0
fi
# precmd () {print -Pn "\e]0;%n@%m: %~\a"}
print -Pn "\e]0;$1\a"
# precmd () {print -Pn "\e]0;$1\a"}
ssh -l root $1
# exec \033]2;test\007


